[project]
name = "youtube-music-twitch-song-request"
version = "0.1.0"
description = "Add song requests from twitch chat to youtube music"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["youtube-music-api-client"]

[tool.uv.sources]
youtube-music-api-client = { workspace = true }

[tool.uv.workspace]
members = ["src/libs/youtube-music-api-client"]
